name: spotify
description: A dart library for interfacing with the Spotify API.
version: 0.0.9
homepage: https://github.com/rinukkusu/spotify-dart
authors:
- rinukkusu <rinukkusu@auen.land>
- Chance Snow <git@chancesnow.me>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3+14
  json_annotation: ^0.2.0

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.9.0
  json_serializable: ^0.5.0
